# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadSaltMap
                                 A QGIS plugin
 cria mapas que dão apoio ao estudo de impaco causado pela despejo de sal nas estradas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-07
        copyright            : (C) 2019 by Lais Baroni UERJ
        email                : laisrbaroni@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoadSaltMap class from file RoadSaltMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .roadsalt_mapbuilder import RoadSaltMap
    return RoadSaltMap(iface)
